lb:
	ansible-playbook -i inventories/hosts.ini playbooks/load-balancing.yml
harbor:
	ansible-playbook -i inventories/hosts.ini playbooks/artifact-server.yml
portainer:
	ansible-playbook -i inventories/hosts.ini playbooks/portainer-server.yml
sonar:
	ansible-playbook -i inventories/hosts.ini playbooks/sonarqube-server.yml
jenkins:
	ansible-playbook -i inventories/hosts.ini playbooks/jenkins-server.yml
deploy:
	ansible-playbook -i inventories/hosts.ini playbooks/deploy-server.yml